connector.name=iceberg
iceberg.catalog.type=NESSIE
iceberg.nessie-catalog.uri=http://nessie:19120/api/v1
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=s3a://crypto-lake/warehouse
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
